version: 2

sources:
  - name: thelook_ecommerce
    description: BigQuery公開データセット
    database: bigquery-public-data
    schema: thelook_ecommerce
    tables:
      - name: products
        description: 商品マスタ
        columns:
          - name: id
            description: 商品ID（主キー）
            tests:
              - unique
              - not_null
          - name: name
            description: 商品名
          - name: brand
            description: ブランド
          - name: category
            description: カテゴリ
          - name: department
            description: 部門（Men/Women）        
          - name: sku
            description: SKU
          - name: cost
            description: 原価
          - name: retail_price
            description: 定価
          - name: distribution_center_id
            description: 配送センターID
      
      - name: orders
        description: 注文ヘッダ
        columns:
          - name: order_id
            description: 注文ID（主キー）
            tests:
              - unique
              - not_null
          - name: user_id
            description: ユーザーID
          - name: status
            description: 注文ステータス
          - name: gender
            description: 性別
          - name: created_at
            description: 注文作成日時
          - name: returned_at
            description: 返品日時
          - name: shipped_at
            description: 出荷日時
          - name: delivered_at
            description: 配達日時
          - name: num_of_item
            description: 商品点数
      
      - name: order_items
        description: 注文明細
        columns:
          - name: id
            description: 注文明細ID（主キー）
            tests:
              - unique
              - not_null
          - name: order_id
            description: 注文ID
          - name: user_id
            description: ユーザーID
          - name: product_id
            description: 商品ID
          - name: inventory_item_id
            description: 在庫ID
          - name: status
            description: 明細ステータス
          - name: created_at
            description: 作成日時
          - name: shipped_at
            description: 出荷日時
          - name: delivered_at
            description: 配達日時
          - name: returned_at
            description: 返品日時
          - name: sale_price
            description: 販売価格
      
      - name: inventory_items
        description: 在庫・原価情報
        columns:
          - name: id
            description: 在庫ID（主キー）
            tests:
              - unique
              - not_null
          - name: product_id
            description: 商品ID
          - name: created_at
            description: 作成日時
          - name: sold_at
            description: 販売日時
          - name: cost
            description: 原価
          - name: product_category
            description: 商品カテゴリ
          - name: product_name
            description: 商品名
          - name: product_brand
            description: ブランド
          - name: product_retail_price
            description: 定価
          - name: product_department
            description: 部門
          - name: product_sku
            description: SKU
          - name: product_distribution_center_id
            description: 配送センターID
